// Generated by scripts/generate_keyboard_layouts.py — do not edit by hand.
//
// Layout and long-press accent data derived from FlorisBoard
// (https://github.com/florisboard/florisboard), licensed under the
// Apache License 2.0. Copyright the FlorisBoard contributors.

struct KeyboardTypingKey: Hashable {
    let lower: String
    let upper: String

    init(_ lower: String, _ upper: String? = nil) {
        self.lower = lower
        self.upper = upper ?? lower
    }

    func label(shifted: Bool) -> String {
        shifted ? upper : lower
    }
}

struct KeyboardTypingLayout: Identifiable, Hashable {
    let code: String
    let name: String
    let toggleLabel: String
    let rows: [[KeyboardTypingKey]]
    let popups: [String: [String]]

    var id: String { code }

    /// False for scripts without letter case (Arabic); the shift key is hidden.
    var hasCase: Bool {
        rows.contains { row in row.contains { $0.lower != $0.upper } }
    }

    func alternates(for key: KeyboardTypingKey, shifted: Bool) -> [String] {
        guard let alts = popups[key.lower] else { return [] }
        return shifted ? alts.map { $0.uppercased() } : alts
    }
}

enum KeyboardLayoutData {
    static let layouts: [KeyboardTypingLayout] = [
        KeyboardTypingLayout(
            code: "en",
            name: "English",
            toggleLabel: "EN",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["æ", "ã", "å", "ā", "à", "á", "â", "ä"],
                "c": ["ç"],
                "e": ["ē", "ê", "é", "è", "ë"],
                "i": ["ì", "ï", "í", "î", "ī"],
                "n": ["ñ", "ń"],
                "o": ["õ", "ō", "œ", "ø", "ò", "ö", "ó", "ô"],
                "s": ["ß"],
                "u": ["ú", "ū", "ü", "û", "ù"],
            ]
        ),
        KeyboardTypingLayout(
            code: "ru",
            name: "Русский",
            toggleLabel: "РУ",
            rows: [
                [.init("й", "Й"), .init("ц", "Ц"), .init("у", "У"), .init("к", "К"), .init("е", "Е"), .init("н", "Н"), .init("г", "Г"), .init("ш", "Ш"), .init("щ", "Щ"), .init("з", "З"), .init("х", "Х")],
                [.init("ф", "Ф"), .init("ы", "Ы"), .init("в", "В"), .init("а", "А"), .init("п", "П"), .init("р", "Р"), .init("о", "О"), .init("л", "Л"), .init("д", "Д"), .init("ж", "Ж"), .init("э", "Э")],
                [.init("я", "Я"), .init("ч", "Ч"), .init("с", "С"), .init("м", "М"), .init("и", "И"), .init("т", "Т"), .init("ь", "Ь"), .init("б", "Б"), .init("ю", "Ю")],
            ],
            popups: [
                "е": ["ё"],
                "ь": ["ъ"],
            ]
        ),
        KeyboardTypingLayout(
            code: "uk",
            name: "Українська",
            toggleLabel: "УК",
            rows: [
                [.init("й", "Й"), .init("ц", "Ц"), .init("у", "У"), .init("к", "К"), .init("е", "Е"), .init("н", "Н"), .init("г", "Г"), .init("ш", "Ш"), .init("щ", "Щ"), .init("з", "З"), .init("х", "Х")],
                [.init("ф", "Ф"), .init("і", "І"), .init("в", "В"), .init("а", "А"), .init("п", "П"), .init("р", "Р"), .init("о", "О"), .init("л", "Л"), .init("д", "Д"), .init("ж", "Ж"), .init("є", "Є")],
                [.init("я", "Я"), .init("ч", "Ч"), .init("с", "С"), .init("м", "М"), .init("и", "И"), .init("т", "Т"), .init("ь", "Ь"), .init("б", "Б"), .init("ю", "Ю")],
            ],
            popups: [
                "г": ["ґ"],
                "ь": ["ʼ", "'"],
                "є": ["—"],
                "і": ["ї"],
            ]
        ),
        KeyboardTypingLayout(
            code: "be",
            name: "Беларуская",
            toggleLabel: "БЕ",
            rows: [
                [.init("й", "Й"), .init("ц", "Ц"), .init("у", "У"), .init("к", "К"), .init("е", "Е"), .init("н", "Н"), .init("г", "Г"), .init("ш", "Ш"), .init("ў", "Ў"), .init("з", "З"), .init("х", "Х")],
                [.init("ф", "Ф"), .init("ы", "Ы"), .init("в", "В"), .init("а", "А"), .init("п", "П"), .init("р", "Р"), .init("о", "О"), .init("л", "Л"), .init("д", "Д"), .init("ж", "Ж"), .init("э", "Э")],
                [.init("я", "Я"), .init("ч", "Ч"), .init("с", "С"), .init("м", "М"), .init("і", "І"), .init("т", "Т"), .init("ь", "Ь"), .init("б", "Б"), .init("ю", "Ю")],
            ],
            popups: [
                "е": ["ё"],
                "ь": ["ъ"],
                "і": ["и"],
            ]
        ),
        KeyboardTypingLayout(
            code: "es",
            name: "Español",
            toggleLabel: "ES",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L"), .init("ñ", "Ñ")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["á", "å", "ą", "æ", "ā", "ª", "à", "ä", "â", "ã"],
                "c": ["č", "ç", "ć"],
                "e": ["é", "ē", "ę", "ė", "ë", "è", "ê"],
                "i": ["í", "ī", "î", "į", "ì", "ï"],
                "n": ["ñ", "ń"],
                "o": ["ó", "º", "ō", "ø", "œ", "õ", "ô", "ö", "ò"],
                "s": ["ß"],
                "u": ["ú", "ū", "ù", "ü", "û"],
            ]
        ),
        KeyboardTypingLayout(
            code: "fr",
            name: "Français",
            toggleLabel: "FR",
            rows: [
                [.init("a", "A"), .init("z", "Z"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("q", "Q"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L"), .init("m", "M")],
                [.init("w", "W"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("'")],
            ],
            popups: [
                "'": ["‚", "‘", "’", "‹", "›"],
                "a": ["à", "ä", "ã", "å", "ā", "ª", "â", "æ", "á"],
                "c": ["ç", "č", "ć"],
                "e": ["é", "ė", "ę", "ē", "ê", "è", "ë"],
                "i": ["î", "ī", "í", "į", "ì", "ï"],
                "n": ["ñ", "ń"],
                "o": ["ô", "º", "ō", "ø", "õ", "ó", "ò", "ö", "œ"],
                "s": ["ß", "š", "ś"],
                "u": ["ù", "ū", "ü", "ú", "û"],
                "y": ["ÿ"],
            ]
        ),
        KeyboardTypingLayout(
            code: "de",
            name: "Deutsch",
            toggleLabel: "DE",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("z", "Z"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L")],
                [.init("y", "Y"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["ä", "æ", "ã", "å", "ā", "â", "à", "á"],
                "c": ["ç"],
                "e": ["é", "ē", "ê", "è", "ë"],
                "i": ["í", "ì", "ï", "î", "ī"],
                "n": ["ñ", "ń"],
                "o": ["ö", "ō", "ø", "õ", "œ", "ó", "ò", "ô"],
                "s": ["š", "ś"],
                "u": ["ü", "ū", "ù", "û", "ú"],
            ]
        ),
        KeyboardTypingLayout(
            code: "it",
            name: "Italiano",
            toggleLabel: "IT",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["à", "ã", "å", "ā", "ª", "á", "â", "ä", "æ"],
                "e": ["è", "ė", "ə", "ę", "ē", "ê", "é", "ë"],
                "i": ["ì", "ī", "ï", "į", "î", "í"],
                "n": ["ñ", "ń"],
                "o": ["ò", "º", "ō", "œ", "ø", "õ", "ö", "ô", "ó"],
                "u": ["ù", "ū", "û", "ú", "ü"],
            ]
        ),
        KeyboardTypingLayout(
            code: "pt",
            name: "Português",
            toggleLabel: "PT",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["ä", "å", "æ", "ª", "á", "ã", "à", "â"],
                "c": ["ç", "ć", "č"],
                "e": ["ë", "ė", "ē", "é", "è", "ê", "ę"],
                "i": ["ī", "ï", "į", "ì", "í", "î"],
                "n": ["ñ", "ń"],
                "o": ["º", "ō", "ø", "œ", "ö", "ò", "ô", "ó", "õ"],
                "u": ["ū", "ù", "ú", "ü", "û"],
            ]
        ),
        KeyboardTypingLayout(
            code: "nl",
            name: "Nederlands",
            toggleLabel: "NL",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["á", "à", "â", "ä"],
                "c": ["ç"],
                "e": ["é", "è", "ë", "ê"],
                "i": ["í", "ì", "ï", "î"],
                "n": ["ñ"],
                "o": ["ó", "ò", "ö", "ô"],
                "u": ["ú", "ù", "ü", "û"],
            ]
        ),
        KeyboardTypingLayout(
            code: "pl",
            name: "Polski",
            toggleLabel: "PL",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["ą", "à"],
                "c": ["ć"],
                "e": ["ę"],
                "l": ["ł"],
                "n": ["ń"],
                "o": ["ó"],
                "s": ["ś"],
                "x": ["ź"],
                "z": ["ż", "ź"],
            ]
        ),
        KeyboardTypingLayout(
            code: "cs",
            name: "Čeština",
            toggleLabel: "CS",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("z", "Z"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L")],
                [.init("y", "Y"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["á"],
                "c": ["č"],
                "d": ["ď"],
                "e": ["ě", "é"],
                "i": ["í"],
                "l": ["ľ", "ĺ"],
                "n": ["ň"],
                "o": ["ó"],
                "r": ["ř", "ŕ"],
                "s": ["š"],
                "t": ["ť"],
                "u": ["ů", "ú"],
                "y": ["ý"],
                "z": ["ž"],
            ]
        ),
        KeyboardTypingLayout(
            code: "sv",
            name: "Svenska",
            toggleLabel: "SV",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P"), .init("å", "Å")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L"), .init("ö", "Ö"), .init("ä", "Ä")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["ä", "à", "â", "ą", "ã", "å", "æ", "á"],
                "c": ["ç", "č", "ć"],
                "d": ["ð", "ď"],
                "e": ["é", "ê", "è", "ë", "ę"],
                "i": ["í", "ï", "ī", "į", "î", "ì"],
                "l": ["ł"],
                "n": ["ń", "ň", "ñ"],
                "o": ["ö", "ō", "õ", "ò", "ô", "ó", "œ", "ø"],
                "r": ["ř"],
                "s": ["ś", "š", "ş", "ß"],
                "t": ["ť", "þ"],
                "u": ["ü", "ū", "ù", "ú", "û"],
                "y": ["ý", "ÿ"],
                "z": ["ź", "ż", "ž"],
                "ä": ["æ"],
                "ö": ["ø", "œ"],
            ]
        ),
        KeyboardTypingLayout(
            code: "fi",
            name: "Suomi",
            toggleLabel: "FI",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "I"), .init("o", "O"), .init("p", "P"), .init("å", "Å")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L"), .init("ö", "Ö"), .init("ä", "Ä")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["ä", "á", "â", "ã", "ā", "å", "æ", "à"],
                "e": ["é", "ē", "ę", "ė", "è", "ë", "ê"],
                "i": ["í", "ī", "ì", "į", "î", "ï"],
                "o": ["ö", "ō", "œ", "ó", "õ", "ò", "ô", "ø"],
                "s": ["š", "ß", "ś"],
                "u": ["ü", "ū", "û", "ú", "ù"],
                "z": ["ž", "ż", "ź"],
                "ä": ["æ"],
                "ö": ["ø"],
            ]
        ),
        KeyboardTypingLayout(
            code: "tr",
            name: "Türkçe",
            toggleLabel: "TR",
            rows: [
                [.init("q", "Q"), .init("w", "W"), .init("e", "E"), .init("r", "R"), .init("t", "T"), .init("y", "Y"), .init("u", "U"), .init("i", "İ"), .init("o", "O"), .init("p", "P")],
                [.init("a", "A"), .init("s", "S"), .init("d", "D"), .init("f", "F"), .init("g", "G"), .init("h", "H"), .init("j", "J"), .init("k", "K"), .init("l", "L")],
                [.init("z", "Z"), .init("x", "X"), .init("c", "C"), .init("v", "V"), .init("b", "B"), .init("n", "N"), .init("m", "M")],
            ],
            popups: [
                "a": ["â"],
                "c": ["ç"],
                "g": ["ğ"],
                "i": ["î"],
                "o": ["ö"],
                "s": ["ş"],
                "u": ["ü", "û"],
            ]
        ),
        KeyboardTypingLayout(
            code: "el",
            name: "Ελληνικά",
            toggleLabel: "ΕΛ",
            rows: [
                [.init(";"), .init("ς", "Σ"), .init("ε", "Ε"), .init("ρ", "Ρ"), .init("τ", "Τ"), .init("υ", "Υ"), .init("θ", "Θ"), .init("ι", "Ι"), .init("ο", "Ο"), .init("π", "Π")],
                [.init("α", "Α"), .init("σ", "Σ"), .init("δ", "Δ"), .init("φ", "Φ"), .init("γ", "Γ"), .init("η", "Η"), .init("ξ", "Ξ"), .init("κ", "Κ"), .init("λ", "Λ")],
                [.init("ζ", "Ζ"), .init("χ", "Χ"), .init("ψ", "Ψ"), .init("ω", "Ω"), .init("β", "Β"), .init("ν", "Ν"), .init("μ", "Μ")],
            ],
            popups: [
                :
            ]
        ),
        KeyboardTypingLayout(
            code: "ar",
            name: "العربية",
            toggleLabel: "AR",
            rows: [
                [.init("ض"), .init("ص"), .init("ث"), .init("ق"), .init("ف"), .init("غ"), .init("ع"), .init("ه"), .init("خ"), .init("ح"), .init("ج")],
                [.init("ش"), .init("س"), .init("ي"), .init("ب"), .init("ل"), .init("ا"), .init("ت"), .init("ن"), .init("م"), .init("ك"), .init("ط")],
                [.init("ذ"), .init("ء"), .init("ؤ"), .init("ر"), .init("ى"), .init("ة"), .init("و"), .init("ز"), .init("ظ"), .init("د")],
            ],
            popups: [
                "ا": ["أ", "آ", "ء", "إ", "ٱ"],
                "ب": ["پ"],
                "ج": ["چ"],
                "ز": ["ژ"],
                "ش": ["ڜ"],
                "ف": ["ڥ", "ڤ", "ڢ"],
                "ق": ["ڨ"],
                "ك": ["ک", "گ"],
                "ل": ["لا", "لإ", "لأ", "لآ"],
                "ه": ["ھ"],
                "ى": ["ئ"],
                "ي": ["ئ", "ى"],
            ]
        ),
        KeyboardTypingLayout(
            code: "hi",
            name: "हिन्दी",
            toggleLabel: "हि",
            rows: [
                [.init("ट", "ठ"), .init("ड", "ढ"), .init("े", "ै"), .init("र", "ृ"), .init("त", "थ"), .init("य", "य़"), .init("ु", "ू"), .init("ि", "ी"), .init("ो", "ौ"), .init("प", "फ़")],
                [.init("ा", "अ"), .init("स", "श"), .init("द", "ध"), .init("फ", " ़"), .init("ग", "घ"), .init("ह", "ः"), .init("ज", "झ"), .init("क", "ख"), .init("ल", "ळ")],
                [.init("ज्ञ", "ज़"), .init("क्ष", "ष"), .init("च", "छ"), .init("व", "्"), .init("ब", "भ"), .init("न", "ण"), .init("म", "ं")],
            ],
            popups: [
                "क": ["क़", "ख़"],
                "ग": ["ग़", "ॻ"],
                "च": [" ॑", " ॒"],
                "ज": ["ज़", "ॼ", "ॹ"],
                "ड": ["ड़", "ढ़"],
                "त": ["त्र"],
                "द": ["ड़", "ॾ", "ढ़", "ॸ"],
                "न": ["ङ", "ऩ", "ञ"],
                "फ": ["फ़"],
                "ब": ["ॿ", "ऽ", "॰"],
                "म": ["ँ", "ऀ"],
                "य": ["ॺ"],
                "र": ["ऋ", "ॠ", "ॄ", "ऱ"],
                "ल": ["ॢ", "ॣ", "ऌ", "ॡ", "ऴ"],
                "व": [" ॓", " ॔"],
                "स": ["श्र", "ष"],
                "ा": ["आ", "ॅ", "ॲ", "ऄ"],
                "ि": ["इ", "ई"],
                "ु": ["उ", "ॶ", "ॷ", " ॖ", "ऊ", " ॗ"],
                "े": ["ए", "ऍ", "ऎ", " ॆ", "ऐ", " ॎ", " ॕ"],
                "ो": ["ओ", "ऒ", " ॊ", " ॏ", "ॵ", "ॐ", "ॉ", "ॳ", "ॴ", " ऺ", " ऻ", "औ", "ऑ"],
            ]
        ),
    ]

    static func layout(for code: String) -> KeyboardTypingLayout? {
        layouts.first { $0.code == code }
    }
}
